/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javachat;

import java.awt.*;
import java.net.*;
import javax.swing.*;
import javax.swing.text.*;

/**
 *
 * @author user
 */
public class JavaChatGui extends javax.swing.JFrame implements Runnable {
	private Socket sock;
	private String userId;
	private String nick;
	private String host;
	private int port;
	private boolean isStop;
	private boolean isSendOne;
	
	
	private StyledDocument doc;
	
	//tabEnabled에 사용될 상수정의
	public static final int LOGIN=0;
	public static final int CHAT_ENTER=1;
	public static final int THEME=2;
	
	public static final int LOGOUT=-1;
	public static final int EXIT=-2;
	
	
	
	public JavaChatGui() {
		initComponents();
		tfHost.setText("localhost");//호스트 란에 기본값 저장
		doc=this.tpMsg.getStyledDocument();
		this.tabEnabled(LOGIN,CHAT_ENTER); //로그인 패널은 활성화, 채팅방 패널은 비활성화.
		this.btLogout.setEnabled(false);//로그아웃 버튼 비활성화
		
		
		
		
	}//------------------ 생성자

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		tabP = new javax.swing.JTabbedPane();
		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jPanel4 = new javax.swing.JPanel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		tfId = new javax.swing.JTextField();
		tfNick = new javax.swing.JTextField();
		tfHost = new javax.swing.JTextField();
		btCon = new javax.swing.JButton();
		btReset = new javax.swing.JButton();
		jPanel2 = new javax.swing.JPanel();
		jScrollPane2 = new javax.swing.JScrollPane();
		tpMsg = new javax.swing.JTextPane();
		tfInput = new javax.swing.JTextField();
		comboColor = new javax.swing.JComboBox<>();
		lbPreview = new javax.swing.JLabel();
		btEmoti = new javax.swing.JButton();
		chk = new javax.swing.JCheckBox();
		jPanel3 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		userTable = new javax.swing.JTable();
		jPanel5 = new javax.swing.JPanel();
		jLabel3 = new javax.swing.JLabel();
		lbId = new javax.swing.JLabel();
		lbNick = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		btLogout = new javax.swing.JButton();
		btRename = new javax.swing.JButton();
		btExit = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("::TIS Talk v1.1::");
		setResizable(false);

		jPanel1.setBackground(new java.awt.Color(255, 255, 255));

		jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/5.PNG"))); // NOI18N

		jLabel2.setBackground(new java.awt.Color(255, 255, 255));
		jLabel2.setFont(new java.awt.Font("한컴 윤고딕 250", 1, 24)); // NOI18N
		jLabel2.setForeground(new java.awt.Color(0, 102, 255));
		jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel2.setText("TIS Talk v1.1");
		jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
		jLabel2.setOpaque(true);

		jLabel6.setFont(new java.awt.Font("굴림", 1, 14)); // NOI18N
		jLabel6.setText("대 화 명 :");

		jLabel7.setFont(new java.awt.Font("굴림", 1, 14)); // NOI18N
		jLabel7.setText("아 이 디 :");

		jLabel8.setFont(new java.awt.Font("굴림", 1, 14)); // NOI18N
		jLabel8.setText("호 스 트 :");

		btCon.setBackground(new java.awt.Color(51, 153, 255));
		btCon.setForeground(new java.awt.Color(255, 255, 255));
		btCon.setMnemonic('C');
		btCon.setText("연    결");
		btCon.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btConActionPerformed(evt);
			}
		});

		btReset.setBackground(new java.awt.Color(51, 153, 255));
		btReset.setForeground(new java.awt.Color(255, 255, 255));
		btReset.setMnemonic('R');
		btReset.setText("다시 쓰기");
		btReset.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btResetActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout.setHorizontalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel4Layout.createSequentialGroup().addContainerGap().addGroup(jPanel4Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel4Layout.createSequentialGroup().addComponent(jLabel8)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(jPanel4Layout.createSequentialGroup().addComponent(btCon)
												.addGap(110, 110, 110).addComponent(btReset))
										.addComponent(tfHost, javax.swing.GroupLayout.PREFERRED_SIZE, 291,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel4Layout.createSequentialGroup().addComponent(jLabel7)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, 312,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										jPanel4Layout.createSequentialGroup().addComponent(jLabel6)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
												.addComponent(tfNick, javax.swing.GroupLayout.PREFERRED_SIZE, 312,
														javax.swing.GroupLayout.PREFERRED_SIZE))))
						.addContainerGap(33, Short.MAX_VALUE)));

		jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] { btCon, btReset });

		jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL,
				new java.awt.Component[] { tfHost, tfId, tfNick });

		jPanel4Layout.setVerticalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						jPanel4Layout.createSequentialGroup().addContainerGap(51, Short.MAX_VALUE)
								.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(34, 34, 34)
								.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(tfNick, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(38, 38, 38)
								.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(tfHost, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(39, 39, 39)
								.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(btReset).addComponent(btCon,
												javax.swing.GroupLayout.PREFERRED_SIZE, 42,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(36, 36, 36)));

		jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] { btCon, btReset });

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						jPanel1Layout.createSequentialGroup().addContainerGap()
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addGroup(jPanel1Layout.createSequentialGroup().addComponent(jLabel1)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
								.addContainerGap()));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap()
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 77,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(32, 32, 32).addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addContainerGap()));

		tabP.addTab("로그인", jPanel1);

		jPanel2.setBackground(new java.awt.Color(255, 255, 255));

		tpMsg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255), 3));
		jScrollPane2.setViewportView(tpMsg);

		tfInput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 153, 255), 3));
		tfInput.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				tfInputActionPerformed(evt);
			}
		});

		comboColor.setModel(
				new javax.swing.DefaultComboBoxModel<>(new String[] { "검정색", "빨강색", "녹   색", "파   랑", "남   색" }));
		comboColor.addItemListener(new java.awt.event.ItemListener() {
			public void itemStateChanged(java.awt.event.ItemEvent evt) {
				comboColorItemStateChanged(evt);
			}
		});

		lbPreview.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
		lbPreview.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		lbPreview.setText("가");
		lbPreview.setBorder(javax.swing.BorderFactory.createEtchedBorder());
		lbPreview.setMaximumSize(new java.awt.Dimension(20, 20));
		lbPreview.setPreferredSize(new java.awt.Dimension(20, 20));

		btEmoti.setText("이모티콘");
		btEmoti.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btEmotiActionPerformed(evt);
			}
		});

		chk.setText("귓  속  말");
		chk.addItemListener(new java.awt.event.ItemListener() {
			public void itemStateChanged(java.awt.event.ItemEvent evt) {
				chkItemStateChanged(evt);
			}
		});

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jScrollPane2).addComponent(tfInput)
				.addGroup(jPanel2Layout.createSequentialGroup().addContainerGap().addComponent(chk).addGap(18, 18, 18)
						.addComponent(comboColor, 0, 200, Short.MAX_VALUE).addGap(18, 18, 18)
						.addComponent(lbPreview, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18).addComponent(btEmoti).addContainerGap()));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup()
						.addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 369,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(tfInput, javax.swing.GroupLayout.PREFERRED_SIZE, 42,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(lbPreview, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(btEmoti))
								.addComponent(comboColor).addComponent(chk, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(0, 12, Short.MAX_VALUE)));

		tabP.addTab("채팅방", jPanel2);

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 462, Short.MAX_VALUE));
		jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 465, Short.MAX_VALUE));

		tabP.addTab("테마색", jPanel3);

		userTable.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {

		}, new String[] { "아이디", "대화명" }));
		userTable.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				userTableMousePressed(evt);
			}
		});
		jScrollPane1.setViewportView(userTable);

		jPanel5.setBackground(new java.awt.Color(255, 255, 204));
		jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "::My Info::",
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION,
				new java.awt.Font("굴림", 1, 12))); // NOI18N

		jLabel3.setFont(new java.awt.Font("굴림", 1, 12)); // NOI18N
		jLabel3.setText("아 이 디 :");

		lbId.setFont(new java.awt.Font("나눔고딕", 1, 14)); // NOI18N

		lbNick.setFont(new java.awt.Font("나눔고딕", 1, 14)); // NOI18N

		jLabel9.setFont(new java.awt.Font("굴림", 1, 12)); // NOI18N
		jLabel9.setText("대 화 명:");

		javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
		jPanel5.setLayout(jPanel5Layout);
		jPanel5Layout.setHorizontalGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel5Layout.createSequentialGroup().addContainerGap().addGroup(jPanel5Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel5Layout.createSequentialGroup().addComponent(jLabel3)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(lbId))
						.addGroup(jPanel5Layout.createSequentialGroup().addComponent(jLabel9)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(lbNick)))
						.addGap(86, 86, 86)));
		jPanel5Layout.setVerticalGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel5Layout.createSequentialGroup().addContainerGap(41, Short.MAX_VALUE)
						.addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel3).addComponent(lbId))
						.addGap(51, 51, 51)
						.addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel9).addComponent(lbNick))
						.addGap(35, 35, 35)));

		btLogout.setBackground(new java.awt.Color(51, 153, 255));
		btLogout.setForeground(new java.awt.Color(255, 255, 255));
		btLogout.setText("퇴  장");
		btLogout.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btLogoutActionPerformed(evt);
			}
		});

		btRename.setBackground(new java.awt.Color(51, 153, 255));
		btRename.setForeground(new java.awt.Color(255, 255, 255));
		btRename.setText("대화명 변경");
		btRename.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btRenameActionPerformed(evt);
			}
		});

		btExit.setBackground(new java.awt.Color(51, 153, 255));
		btExit.setForeground(new java.awt.Color(255, 255, 255));
		btExit.setText("종  료");
		btExit.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btExitActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addContainerGap()
				.addComponent(tabP, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
						.addGroup(layout.createSequentialGroup().addComponent(btLogout)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40,
										Short.MAX_VALUE)
								.addComponent(btRename).addGap(37, 37, 37).addComponent(btExit)))
				.addContainerGap()));

		layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] { btExit, btLogout, btRename });

		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup().addContainerGap().addGroup(layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
						.addGroup(layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE)
								.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(btLogout)
										.addComponent(btRename, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(btExit))
								.addGap(8, 8, 8))
						.addComponent(tabP)).addContainerGap()));

		layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] { btExit, btLogout, btRename });

		pack();
	}// </editor-fold>//GEN-END:initComponents

	/** 연결 버튼 작동 이벤트 */
	private void btConActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btConActionPerformed
		check();

	}// --------------연결버튼--------------------

	private void btResetActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btResetActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_btResetActionPerformed

	private void btLogoutActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btLogoutActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_btLogoutActionPerformed

	private void btRenameActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btRenameActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_btRenameActionPerformed

	private void btExitActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btExitActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_btExitActionPerformed

	private void btEmotiActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btEmotiActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_btEmotiActionPerformed

	private void tfInputActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tfInputActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_tfInputActionPerformed

	private void chkItemStateChanged(java.awt.event.ItemEvent evt) {// GEN-FIRST:event_chkItemStateChanged
		// TODO add your handling code here:
	}// GEN-LAST:event_chkItemStateChanged

	private void comboColorItemStateChanged(java.awt.event.ItemEvent evt) {// GEN-FIRST:event_comboColorItemStateChanged
		// TODO add your handling code here:
	}// GEN-LAST:event_comboColorItemStateChanged

	private void userTableMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_userTableMousePressed
		// TODO add your handling code here:
	}// GEN-LAST:event_userTableMousePressed

	/**
	 * @param args the command line arguments
	 */
	public void run() {

	}

	public void parsing(String msg) {

	}

	public void logout(String id, String nick, int mode) {

	}

	public void exitChat(int mode) {

	}

	public void exitProcess() {

	}

	public void sendMessage(String msg) {

	}

	public void showChat(String from, String fontRGB, String fromMsg) {

	}

	public void showChat(Color fgCr, Color bgCr, String msg) {

	}

	public void chatEnter() {

	}
	/**아이디, 대화명 확인 메소드*/
	public void check() {
	//사용자가 입력한 값 얻기
		userId = tfId.getText();
    	nick =tfNick.getText();
    	this.host=tfHost.getText();
    	   	
    	//유효성 체크
    	if(userId==null||nick==null||host==null||userId.trim().isEmpty()||nick.trim().isEmpty()||host.trim().isEmpty()) { 
    		showMsg("아이디, 대화명,접속할 서버의 호스트명을 입력하세요");
    		tfId.requestFocus();
    		return;
    	}
    	
    	//채팅방에 입장하는 메소드 호출
    	chatEnter();
    
	}

	private void showMsg(String str) {
		JOptionPane.showMessageDialog(this, str);
	}

	public void tabEnabled(int enabled, int disabled) {
		tabP.setEnabledAt(enabled, true);
		tabP.setEnabledAt(disabled, false);
		if(enabled==LOGIN) {
			tfId.requestFocus();
		}else if (enabled==CHAT_ENTER) {
			tfInput.requestFocus();
			btLogout.setEnabled(true);//로그아웃 버튼 활성화
		}/////if
		
		
	}//---------------------------------------

	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(JavaChatGui.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(JavaChatGui.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(JavaChatGui.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(JavaChatGui.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new JavaChatGui().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btCon;
	private javax.swing.JButton btEmoti;
	private javax.swing.JButton btExit;
	private javax.swing.JButton btLogout;
	private javax.swing.JButton btRename;
	private javax.swing.JButton btReset;
	private javax.swing.JCheckBox chk;
	private javax.swing.JComboBox<String> comboColor;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel5;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JLabel lbId;
	private javax.swing.JLabel lbNick;
	private javax.swing.JLabel lbPreview;
	private javax.swing.JTabbedPane tabP;
	private javax.swing.JTextField tfHost;
	private javax.swing.JTextField tfId;
	private javax.swing.JTextField tfInput;
	private javax.swing.JTextField tfNick;
	private javax.swing.JTextPane tpMsg;
	private javax.swing.JTable userTable;
	// End of variables declaration//GEN-END:variables
}
