/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mynotepad;

import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class NotePad extends javax.swing.JFrame {

	/**
	 * Creates new form NotePad
	 */
	public NotePad() {
		super("::NotePad::");
		initComponents();
		
	}//»ý¼ºÀÚ =================================================
	
	

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jButton1 = new javax.swing.JButton();
		jMenuItem1 = new javax.swing.JMenuItem();
		jMenuItem2 = new javax.swing.JMenuItem();
		jToolBar1 = new javax.swing.JToolBar();
		btNew = new javax.swing.JButton();
		btOpen = new javax.swing.JButton();
		btSave = new javax.swing.JButton();
		filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0),
				new java.awt.Dimension(32767, 0));
		btHelp = new javax.swing.JButton();
		jSplitPane1 = new javax.swing.JSplitPane();
		jPanel1 = new javax.swing.JPanel();
		jPanel3 = new javax.swing.JPanel();
		tfDir = new javax.swing.JTextField();
		jScrollPane1 = new javax.swing.JScrollPane();
		list = new javax.swing.JList<>();
		jPanel2 = new javax.swing.JPanel();
		jScrollPane2 = new javax.swing.JScrollPane();
		ta = new javax.swing.JTextArea();
		jScrollPane3 = new javax.swing.JScrollPane();
		lb = new javax.swing.JLabel();

		jButton1.setText("jButton1");

		jMenuItem1.setText("jMenuItem1");

		jMenuItem2.setText("jMenuItem2");

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jToolBar1.setRollover(true);

		btNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new.PNG"))); // NOI18N
		btNew.setFocusable(false);
		btNew.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		btNew.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		btNew.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btNewActionPerformed(evt);
			}
		});
		jToolBar1.add(btNew);

		btOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/open.PNG"))); // NOI18N
		btOpen.setFocusable(false);
		btOpen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		btOpen.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		btOpen.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btOpenActionPerformed(evt);
			}
		});
		jToolBar1.add(btOpen);

		btSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.PNG"))); // NOI18N
		btSave.setFocusable(false);
		btSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		btSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		btSave.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btSaveActionPerformed(evt);
			}
		});
		jToolBar1.add(btSave);
		jToolBar1.add(filler1);

		btHelp.setFont(new java.awt.Font("±¼¸²", 1, 12)); // NOI18N
		btHelp.setText("Help");
		btHelp.setFocusable(false);
		btHelp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		btHelp.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		btHelp.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btHelpActionPerformed(evt);
			}
		});
		jToolBar1.add(btHelp);

		jSplitPane1.setDividerLocation(150);
		jSplitPane1.setDividerSize(7);
		jSplitPane1.setName(""); // NOI18N
		jSplitPane1.setOneTouchExpandable(true);

		tfDir.setBorder(javax.swing.BorderFactory.createTitledBorder("::Directory::"));
		tfDir.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				tfDirActionPerformed(evt);
			}
		});

		list.setBorder(javax.swing.BorderFactory.createTitledBorder("::List::"));
		list.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
			public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
				listValueChanged(evt);
			}
		});
		jScrollPane1.setViewportView(list);

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(tfDir, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
				.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE));
		jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup()
						.addComponent(tfDir, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)));

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(
				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jPanel3,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		jSplitPane1.setLeftComponent(jPanel1);

		ta.setColumns(20);
		ta.setRows(5);
		ta.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 3, true));
		jScrollPane2.setViewportView(ta);

		lb.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
		lb.setForeground(new java.awt.Color(153, 153, 153));
		lb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		lb.setText("No Image");
		jScrollPane3.setViewportView(lb);

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup()
						.addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 544,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
				.addComponent(jScrollPane3));

		jSplitPane1.setRightComponent(jPanel2);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jToolBar1,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addComponent(jSplitPane1));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(jSplitPane1)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	public void showMsg(String msg) {
		JOptionPane.showMessageDialog(this, msg);
	}

	private void btNewActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btNewActionPerformed
		showMsg("¾È³ç?? New");
	}// GEN-LAST:event_btNewActionPerformed

	private void btOpenActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btOpenActionPerformed
		showMsg("ÇÏÀÌ? Open");
	}// GEN-LAST:event_btOpenActionPerformed

	private void btSaveActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btSaveActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_btSaveActionPerformed

	private void btHelpActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btHelpActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_btHelpActionPerformed

	private void tfDirActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tfDirActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_tfDirActionPerformed

	private void listValueChanged(javax.swing.event.ListSelectionEvent evt) {// GEN-FIRST:event_listValueChanged
		// TODO add your handling code here:
	}// GEN-LAST:event_listValueChanged

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				System.out.println(info.getName());
				if ("windows".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(NotePad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(NotePad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(NotePad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(NotePad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				
					new NotePad().setVisible(true);
				
			}
		});
	}////////////// main-----------------------------

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btHelp;
	private javax.swing.JButton btNew;
	private javax.swing.JButton btOpen;
	private javax.swing.JButton btSave;
	private javax.swing.Box.Filler filler1;
	private javax.swing.JButton jButton1;
	private javax.swing.JMenuItem jMenuItem1;
	private javax.swing.JMenuItem jMenuItem2;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JSplitPane jSplitPane1;
	private javax.swing.JToolBar jToolBar1;
	private javax.swing.JLabel lb;
	private javax.swing.JList<String> list;
	private javax.swing.JTextArea ta;
	private javax.swing.JTextField tfDir;
	// End of variables declaration//GEN-END:variables
}////// class
